; Intruder Alert data generated by FamiStudio from intruder_alert.nsf.
; Channel 4 (DPCM) replaced with a valid inactive sentinel for this NES ROM.

; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Intruder Alert:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1

music_data_intruder_alert:
DB 1
DW .instruments
DW .samples-4
; 00 : Song 1
DW .song0ch0
DW .song0ch1
DW .song0ch2
DW .song0ch3
DW .song0ch4
DB (.tempo_env_1_mid & $FF), (.tempo_env_1_mid >> 8), 0, 0

.instruments:
DW .env1,.env2,.env5,.env0 ; 00 : Duty 1
DW .env1,.env2,.env4,.env0 ; 01 : Duty 2
DW .env1,.env2,.env3,.env0 ; 02 : Duty 0

.env0:
DB $00,$c0,$7f,$00,$02
.env1:
DB $00,$cf,$7f,$00,$02
.env2:
DB $c0,$7f,$00,$01
.env3:
DB $7f,$00,$00
.env4:
DB $c2,$7f,$00,$00
.env5:
DB $c1,$7f,$00,$00

.samples:
DB $00+(FAMISTUDIO_DPCM_PTR & $FF),$16,$0f,$40 ; 00 Sample 1 (Pitch:15)
DB $06+(FAMISTUDIO_DPCM_PTR & $FF),$1b,$0f,$40 ; 01 Sample 2 (Pitch:15)
DB $0d+(FAMISTUDIO_DPCM_PTR & $FF),$20,$0f,$40 ; 02 Sample 3 (Pitch:15)
DB $15+(FAMISTUDIO_DPCM_PTR & $FF),$2f,$0f,$40 ; 03 Sample 4 (Pitch:15)

.tempo_env_1_mid:
DB $03,$05,$80

.song0ch0:
.song0ch0loop:
DB $47, (.tempo_env_1_mid & $FF), (.tempo_env_1_mid >> 8), $7c
.song0ref6:
DB $80
.song0ref7:
DB $0d, $85, $7b, $83, $7c, $0f, $85, $7b, $83, $77, $83, $76, $87, $75, $83, $74, $87, $7c, $87, $7b, $83, $77, $83, $76
DB $87, $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0a
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
.song0ref48:
DB $7c, $0a, $85, $7b, $87, $7a, $83, $79, $83, $7c, $0c, $85, $7b, $87, $7a, $83, $79, $83, $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0b
DW .song0ref7
DB $48, $7b, $83, $77, $83, $76, $87, $7c
DB $41, $0a
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
.song0ref93:
DB $7c, $4e, $ff, $84, $11, $4e, $fd, $12, $7b, $4e, $fc, $13, $14
.song0ref106:
DB $7a
.song0ref107:
DB $4e, $fe, $81, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81
.song0ref119:
DB $4e, $fc, $83, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $81, $4e, $fd, $81
DB $4e, $fe, $81, $74, $4e, $00, $11, $4e, $ff, $12, $4e, $fe, $13, $4e, $fc, $14, $81, $4e, $fe, $81, $7c, $4e, $00
DB $41, $0e
DW .song0ref6
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0a
DW .song0ref7
DB $7c
DB $41, $0d
DW .song0ref7
DB $48, $76, $87, $7c
DB $41, $0e
DW .song0ref7
DB $41, $0a
DW .song0ref48
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0a
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $41, $11
DW .song0ref93
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $48
.song0ref230:
DB $7c, $4e, $00, $80
.song0ref234:
DB $0d, $85, $7b, $83, $7c, $0f, $85, $7b, $83, $74, $0d, $89, $0f, $89, $7c, $87, $7b, $83, $77, $83, $76, $87, $7c
DB $41, $0e
DW .song0ref234
.song0ref260:
DB $7c, $0d, $85, $7b, $83, $7c, $0f, $85, $7b, $87, $7a, $83, $79, $83, $78, $87, $77, $83, $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
.song0ref286:
DB $7c, $14, $85, $7b, $87, $7a, $83, $79, $83, $7c, $0f, $85, $7b, $87, $7a, $83, $79, $83, $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0b
DW .song0ref234
DB $48, $7b, $83, $77, $83, $76, $87
DB $41, $0a
DW .song0ref260
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c, $4e, $ff, $84, $13, $4e, $fd, $14, $7b, $4e, $fc, $15, $16
DB $41, $0d
DW .song0ref106
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81
DB $41, $0e
DW .song0ref230
DB $7c
DB $41, $0e
DW .song0ref234
DB $41, $0a
DW .song0ref260
DB $7c
DB $41, $0d
DW .song0ref234
DB $48, $76, $87, $7c
DB $41, $0e
DW .song0ref234
DB $41, $0a
DW .song0ref286
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
DB $41, $0a
DW .song0ref260
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c, $4e, $ff, $84, $13, $4e, $fd, $14, $7b, $4e, $fc, $15, $16
DB $41, $0d
DW .song0ref106
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $48
.song0ref436:
DB $78, $4e, $00, $80
.song0ref440:
DB $1d, $79, $83, $7a, $85, $78, $1e
.song0ref447:
DB $79, $83, $7a, $85
.song0ref451:
DB $75, $97
.song0ref453:
DB $78, $81
.song0ref455:
DB $79, $83
.song0ref457:
DB $7a
.song0ref458:
DB $85
.song0ref459:
DB $7b, $8b
.song0ref461:
DB $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $7a, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff
DB $81, $4e, $fe, $81, $79, $4e, $fd, $81, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e
DB $ff, $81, $78, $4e, $fe, $81, $75, $4e, $fd, $81, $4e, $fc, $85
.song0ref522:
DB $4e, $fe, $83, $4e, $00, $81, $74, $81, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e
DB $ff, $81, $4e, $00, $81, $78, $81, $79, $83, $7a, $85, $78, $1d, $79, $83, $7a, $85, $78, $1b, $79, $83, $7a, $85, $78
DB $41, $28
DW .song0ref440
.song0ref573:
DB $78, $1b, $79, $83, $7a, $85, $78, $1d, $79, $83, $7a, $85, $78, $1e, $79, $83, $7a, $85, $78, $1d
DB $41, $14
DW .song0ref455
.song0ref596:
DB $4e, $fd, $81, $4e, $fc, $85, $4e, $fe, $83, $4e, $00, $81, $77, $81, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $4e
DB $fd, $81, $76, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $83
DB $78, $4e, $00, $20, $79, $83, $7a, $81, $48, $83, $7b, $97, $78, $81, $79, $83, $7a, $85, $78, $4e, $ff, $1f, $79, $4e
DB $fd, $1e, $4e, $00, $81
DB $41, $13
DW .song0ref457
.song0ref676:
DB $4e, $fd, $81, $4e, $fc, $85, $4e, $fe, $83, $4e, $00, $81, $77, $81
.song0ref690:
DB $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $81, $74, $83, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e
DB $ff, $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $83, $73, $81, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00
DB $83, $4e, $ff, $81, $72, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $85, $7a, $4e, $00, $84, $0a, $0b, $79, $0c, $0d, $78
DB $8f, $7a, $80, $0f, $85, $79, $87, $78, $83, $77, $83, $7a, $11, $85, $79, $87, $78, $83, $77, $83, $78
DB $41, $31
DW .song0ref440
DB $78
DB $41, $0a
DW .song0ref440
DB $7b, $83, $48, $87
DB $41, $1d
DW .song0ref461
DB $41, $0a
DW .song0ref573
DB $41, $14
DW .song0ref455
DB $41, $12
DW .song0ref596
.song0ref806:
DB $7a, $85, $7b, $8b, $75, $8b, $78, $81, $79, $83, $7a, $85, $78, $4e, $f8, $81, $79, $4e, $00, $21, $4e, $07, $22, $7a
DB $4e, $00
DB $41, $13
DW .song0ref458
DB $41, $10
DW .song0ref596
.song0ref838:
DB $75, $81, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $74, $4e, $fe, $81, $4e, $fd, $81
DB $4e, $fc, $85, $4e, $fe, $83, $4e, $00, $83, $73, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe
DB $81, $72, $4e, $ff, $81, $71
.song0ref892:
DB $4e, $00, $83, $4e, $ff, $81
.song0ref898:
DB $4e, $fe, $81
.song0ref901:
DB $4e, $fd, $81, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81
DB $4e, $fd, $81, $4e, $fc, $81, $00, $4e, $00, $89, $48, $78
DB $41, $28
DW .song0ref440
DB $78, $20, $79, $83, $7a, $85, $78, $1e, $79, $83, $7a, $85
DB $41, $09
DW .song0ref573
DB $41, $16
DW .song0ref451
.song0ref958:
DB $4e, $00, $19, $79, $83, $7a, $85, $7b, $8b, $78, $1b, $79, $83, $7a, $85, $7b, $8b, $78, $1d, $79, $83, $7a, $85, $77
DB $8b, $78, $81, $79, $83, $7a, $85, $78, $4e, $f8, $81, $79, $4e, $03, $1e, $4e, $00, $81, $7a, $85, $7b, $8b, $77, $8b
DB $41, $15
DW .song0ref453
DB $4e, $fd, $81, $4e, $fc, $85, $48
.song0ref1016:
DB $4e, $fe, $83, $4e, $00, $81, $77, $81, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $81, $78, $4e, $00, $22, $79, $83, $7a
DB $85, $7b, $8b, $78, $20
DB $41, $14
DW .song0ref455
DB $41, $16
DW .song0ref676
.song0ref1051:
DB $78, $81, $79, $83, $7a, $85, $78, $1e, $79, $83, $7a, $85, $78, $1b, $79, $83, $7a, $85, $78, $19, $79, $83, $7a, $85
DB $78, $1b, $79, $83, $7a, $85, $78, $1e, $79, $83, $7a, $85, $78, $20, $79, $83, $7a, $85, $78, $1e, $79, $83, $7a, $85
DB $78, $20
DB $41, $18
DW .song0ref447
.song0ref1104:
DB $4e, $00, $22, $79, $83, $7a, $85, $7b, $8b, $78, $25, $79, $83, $7a, $85, $7b, $8b, $78, $22, $79, $83, $7a, $85, $7b
DB $8b, $78, $1e, $79, $83, $7a, $85, $78, $20, $79, $83, $7a, $85, $75, $97, $78, $81, $79, $83, $7a, $85, $7b, $83, $48
DB $87
DB $41, $11
DW .song0ref461
.song0ref1156:
DB $4e, $00, $22, $79, $83, $7a, $85, $7b, $8b, $78, $25, $79, $83, $7a, $85, $7b, $8b, $78, $27, $79, $83, $7a, $85, $7b
DB $8b
.song0ref1181:
DB $78, $25, $79, $83, $7a, $85, $78, $4e, $fc, $26, $79, $4e, $00, $27, $81, $7a, $85, $75, $8b, $78, $25, $79, $83, $7a
DB $85, $78, $4e, $fc, $26, $79, $4e, $00, $27, $81, $7a, $85, $77, $8b, $78, $25, $79, $83, $7a, $85, $78, $27, $79, $83
DB $7a, $85, $78, $25, $79, $83, $7a, $85, $77, $8b, $78, $22, $79, $83, $7a, $85, $78, $8b, $20, $79, $83, $7a, $85, $78
DB $8b, $1e, $79, $83, $7a, $85, $79, $8b, $78, $27
.song0ref1263:
DB $79, $83, $7a, $85, $78, $25, $79, $83, $7a, $85, $78, $22, $79, $83, $7a, $85, $78, $20
DB $41, $09
DW .song0ref1263
.song0ref1284:
DB $79, $83, $7a, $85, $78, $1e, $79, $83, $7a, $85, $78, $22
.song0ref1296:
DB $79, $83, $7a, $85, $78, $20, $79, $83, $7a, $85, $78, $1e, $79, $83, $7a, $85, $78, $1b
DB $41, $09
DW .song0ref1296
DB $79, $83, $7a, $85, $78, $19, $79, $83, $7a, $85, $48
.song0ref1328:
DB $78, $4e, $f8, $81, $79, $4e, $08, $1a, $4e, $00, $81, $7a, $4e, $f8, $81, $4e, $07, $1b, $4e, $00, $81, $7b, $97, $7a
DB $8b, $4e, $ff, $81, $79, $4e, $fe, $83, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $78
DB $4e, $ff, $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $77, $4e, $ff, $81, $4e, $00
DB $83, $4e, $ff, $81, $4e, $fe, $81, $4e, $f9, $81, $4e, $f7, $83, $76
.song0ref1414:
DB $4e, $f8, $81, $4e, $fb, $81, $4e, $fd, $81, $4e, $ff, $81, $4e, $00, $81, $4e, $ff, $81, $4e, $fc, $81, $4e, $fb, $81
DB $4e, $f8, $81, $75, $4e, $f7, $83, $4e, $f9, $81, $4e, $fb, $81
.song0ref1451:
DB $4e, $fe, $81, $4e, $00, $83, $74, $4e, $fe, $81, $4e, $fb, $81, $4e, $fa, $81, $4e, $f7, $83, $4e, $09, $1c, $4e, $f7
DB $1b, $4e, $fa, $81, $4e, $fe, $81, $73, $4e, $00, $81, $4e, $ff, $81, $4e, $fc, $81, $4e, $f9, $81, $4e, $f6, $81, $4e
DB $08, $1c, $81, $4e, $0a, $81, $4e, $f9, $1b, $72, $4e, $fc, $81, $4e, $ff, $81, $4e, $00, $81, $4e, $fe, $81, $4e, $fb
DB $81, $4e, $f8, $81, $4e, $0a, $1c, $4e, $08, $81, $71, $81, $4e, $f6, $1b, $4e, $f9, $81, $4e, $fd, $81, $4e, $ff, $81
DB $4e, $00, $81, $4e, $fd, $81, $4e, $fa, $81, $4e, $f7, $81, $00, $4e, $00, $ff, $b1, $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0b
DW .song0ref7
DB $48, $7b, $83, $77, $83, $76, $87, $7c
DB $41, $0a
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $41, $0a
DW .song0ref48
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0a
DW .song0ref7
DB $7c
DB $41, $0d
DW .song0ref7
DB $48, $76, $87, $7c
DB $41, $0e
DW .song0ref7
DB $41, $17
DW .song0ref93
DB $7c, $4e, $00
DB $41, $0e
DW .song0ref6
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0a
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $41, $0a
DW .song0ref48
DB $48, $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0a
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $7c
DB $41, $0e
DW .song0ref7
DB $41, $11
DW .song0ref93
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81
DB $41, $0e
DW .song0ref230
DB $7c
DB $41, $0b
DW .song0ref234
DB $48, $7b, $83, $77, $83, $76, $87
DB $41, $0a
DW .song0ref260
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
DB $41, $0a
DW .song0ref286
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
DB $41, $0a
DW .song0ref260
DB $7c
DB $41, $0d
DW .song0ref234
DB $48, $76, $87, $7c
DB $41, $0e
DW .song0ref234
DB $7c, $4e, $ff, $84, $13, $4e, $fd, $14, $7b, $4e, $fc, $15, $16
DB $41, $0d
DW .song0ref106
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81
DB $41, $0e
DW .song0ref230
DB $7c
DB $41, $0e
DW .song0ref234
DB $41, $0a
DW .song0ref260
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
DB $41, $0a
DW .song0ref286
DB $48, $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
DB $41, $0a
DW .song0ref260
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c
DB $41, $0e
DW .song0ref234
DB $7c, $4e, $ff, $84, $13, $4e, $fd, $14, $7b, $4e, $fc, $15, $16
DB $41, $0d
DW .song0ref106
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81
DB $41, $1e
DW .song0ref436
DB $48
DB $41, $13
DW .song0ref522
DB $78
DB $41, $28
DW .song0ref440
DB $41, $0a
DW .song0ref573
DB $41, $14
DW .song0ref455
DB $41, $12
DW .song0ref596
DB $7a, $85, $7b, $97, $78, $81, $79, $83, $7a, $85, $78, $4e, $ff, $1f, $79, $4e, $fd, $1e, $4e, $00, $81
DB $41, $13
DW .song0ref457
DB $4e, $fd, $81, $4e, $fc, $85, $4e, $fe, $83, $4e, $00, $81, $77, $81, $48
DB $41, $24
DW .song0ref690
DB $78
DB $41, $31
DW .song0ref440
DB $78
DB $41, $28
DW .song0ref440
DB $41, $09
DW .song0ref573
DB $48, $78, $1d
DB $41, $14
DW .song0ref455
DB $41, $12
DW .song0ref596
DB $41, $09
DW .song0ref806
DB $7a, $4e, $00
DB $41, $13
DW .song0ref458
DB $41, $10
DW .song0ref596
DB $41, $20
DW .song0ref838
DB $78
DB $41, $1e
DW .song0ref440
DB $48
DB $41, $0a
DW .song0ref522
DB $78, $20, $79, $83, $7a, $85, $78, $1e, $79, $83, $7a, $85
DB $41, $09
DW .song0ref573
DB $41, $16
DW .song0ref451
DB $41, $15
DW .song0ref958
DB $41, $15
DW .song0ref453
DB $4e, $fd, $81, $4e, $fc, $85
DB $41, $0b
DW .song0ref1016
DB $41, $14
DW .song0ref455
DB $4e, $fd, $81, $4e, $fc, $85, $4e, $fe, $83, $4e, $00, $81, $77, $81, $48
DB $41, $11
DW .song0ref690
DB $41, $19
DW .song0ref1051
DB $41, $18
DW .song0ref447
DB $41, $16
DW .song0ref1104
DB $41, $12
DW .song0ref459
DB $41, $0c
DW .song0ref1156
DB $48
DB $41, $30
DW .song0ref1181
DB $41, $09
DW .song0ref1263
DB $41, $0f
DW .song0ref1284
DB $41, $09
DW .song0ref1296
DB $79, $83, $7a, $85, $78, $19, $79, $83, $7a, $85
DB $41, $27
DW .song0ref1328
DB $48
DB $41, $27
DW .song0ref1451
DB $7c, $0d, $87, $7b, $81, $7c, $4e, $f8, $81, $4e, $f0, $81, $4e, $e8, $81, $4e, $10, $0e, $4e, $08, $81, $4e, $00, $81
DB $4e, $f8, $81, $4e, $f0, $81, $4e, $15, $0f, $4e, $0d, $81, $4e, $05, $81, $4e, $00, $a5, $4e, $ff, $81, $4e, $fe, $83
DB $4e, $fc, $83, $7b, $81, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81, $4e
DB $fd, $81, $7a, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81
DB $79, $4e, $fd, $81, $4e, $fc, $85, $4e, $fe, $83, $4e, $00, $81, $78, $81, $4e, $ff, $81, $4e, $fe, $83, $77, $4e, $fc
DB $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $76
DB $41, $0b
DW .song0ref898
DB $75, $83, $4e, $fe, $83, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $83, $74, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81
DB $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $73
DB $41, $0a
DW .song0ref898
DB $4e, $fc, $85, $48, $4e, $fe, $81, $72, $81
.song0ref2227:
DB $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83
DB $4e, $ff, $81, $7c, $4e, $00, $89, $7b, $8d, $77, $83, $76, $93, $7c, $0d, $87, $7b, $8d
.song0ref2269:
DB $7c, $12, $87
.song0ref2272:
DB $7b, $8d, $4e, $ff, $81, $4e, $fe, $81, $7a, $81, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00
DB $83, $4e, $ff, $81, $79, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $78, $4e, $ff, $81
DB $4e, $00, $83, $4e, $ff, $81, $77, $4e, $fe, $81, $7c, $4e, $00, $11, $87, $7b, $8d, $7c, $4e, $f8, $10, $4e, $ed, $0f
DB $4e, $0d, $81, $4e, $00, $0e, $4e, $f0, $0d, $4e, $00, $97
DB $41, $13
DW .song0ref2272
DB $4e, $fd, $81, $4e, $fc, $85, $4e, $fe, $83, $4e, $00, $83, $76, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $81, $7c, $4e
DB $00, $14, $87, $7b, $91, $7a, $93
DB $41, $15
DW .song0ref2269
DB $7c, $4e, $00, $0d, $87, $7b, $91, $7a, $93, $76, $8d, $75, $87, $74, $81, $48
.song0ref2409:
DB $7c, $89, $7b, $81, $7c, $4e, $f0, $81, $4e, $10, $0e, $4e, $00, $81, $4e, $f0, $81, $4e, $0d, $0f, $4e, $00, $97, $7b
DB $81, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $7a, $4e, $ff, $81, $4e, $00, $83, $4e
DB $ff, $81, $76
DB $41, $09
DW .song0ref898
DB $7c, $4e, $00, $89, $7b, $8d, $7c, $0d, $87, $7b, $8d, $77, $83, $76, $93
DB $41, $11
DW .song0ref2409
DB $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $85, $4e, $fd, $81, $79, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff
DB $81, $4e, $fe, $81, $4e, $fd, $81, $78, $4e, $fc, $85, $4e, $fe, $81, $77, $81, $4e, $00, $83
DB $41, $0c
DW .song0ref690
DB $7c, $4e, $00, $89, $7b, $8d, $7c, $11, $87, $7b, $8d, $7c, $12, $87, $7b, $8d, $77, $83, $76, $93, $7c, $11, $87, $7b
DB $8d, $7c, $0d, $87, $7b, $91, $7a, $93, $79, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $4e, $fd, $81, $78, $4e, $fe
DB $81, $4e, $ff, $81, $4e, $00, $83, $77, $4e, $ff, $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $83, $48, $81, $4e, $fd
DB $81, $4e, $fe, $81, $4e, $ff, $81, $76, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $85, $4e
DB $fe, $83, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81, $75, $81, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff
DB $81, $4e, $00, $83, $74, $4e, $ff, $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $83, $7c, $4e, $00, $14, $87, $7b, $ff
DB $ff, $ff, $b5, $42
DW .song0ch0loop
.song0ch1:
.song0ch1loop:
.song0ref2678:
DB $7a, $84
.song0ref2680:
DB $14, $80, $14, $79, $83, $78, $83, $74, $83, $73, $83, $72, $83, $74, $0d, $89, $0f, $91, $73, $87, $72, $87
DB $41, $0d
DW .song0ref2678
DB $41, $0a
DW .song0ref2678
DB $89
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
.song0ref2715:
DB $7c, $87, $7b, $87, $7a, $83, $79, $83, $7c, $11, $85, $7b, $87, $7a, $83, $79, $83
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $41, $0a
DW .song0ref2678
DB $89
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $7c, $4e, $ff, $84, $0a, $4e, $fd, $0b, $7b, $4e, $fc, $0c, $0d
DB $41, $0d
DW .song0ref106
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00
DB $41, $0d
DW .song0ref2680
DB $41, $0d
DW .song0ref2678
DB $41, $0a
DW .song0ref2678
DB $89
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $41, $09
DW .song0ref2715
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $41, $0a
DW .song0ref2678
DB $89
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $7c, $4e, $ff, $84, $16, $4e, $fd, $17, $7b, $4e, $fc, $18, $19
DB $41, $0d
DW .song0ref106
.song0ref2832:
DB $74, $4e, $00, $16, $4e, $ff, $17, $4e, $fe, $18, $4e, $fc, $19
.song0ref2845:
DB $81, $4e, $fe, $81, $7c, $4e, $00, $80
.song0ref2853:
DB $14, $85, $7b, $83, $7c, $16, $85, $7b, $83, $74, $14, $89, $16, $89, $7c, $87, $7b, $83, $77, $83, $76, $87, $7c
DB $41, $0e
DW .song0ref2853
.song0ref2879:
DB $7c, $14, $85, $7b, $83, $7c, $16, $85, $7b, $87, $7a, $83, $79, $83, $78, $87, $77, $83, $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
.song0ref2905:
DB $7c, $19, $85, $7b, $87, $7a, $83, $79, $83, $7c, $16, $85, $7b, $87, $7a, $83, $79, $83, $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2879
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c, $4e, $ff, $84, $18, $4e, $fd, $19, $7b, $4e, $fc, $1a, $1b
DB $41, $0d
DW .song0ref106
DB $74, $4e, $00, $18, $4e, $ff, $19, $4e, $fe, $1a, $4e, $fc, $1b
DB $41, $10
DW .song0ref2845
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2879
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2905
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2879
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c, $4e, $ff, $84, $18, $4e, $fd, $19, $7b, $4e, $fc, $1a, $1b
DB $41, $0d
DW .song0ref106
.song0ref3027:
DB $74, $4e, $00, $18, $4e, $ff, $19, $4e, $fe, $1a, $4e, $fc, $1b
.song0ref3040:
DB $81, $4e, $fe, $81, $7b, $4e, $00, $80
.song0ref3048:
DB $0d, $81, $7a, $4e, $fe, $82, $0d, $4e, $fc, $81, $79, $81, $4e, $fd, $81, $7b, $4e, $ff, $80, $0f, $4e, $00, $81, $7a
DB $4e, $ff, $82, $0f
.song0ref3076:
DB $4e, $fd, $81, $79, $4e, $fc, $83, $74, $4e, $fe, $84, $1d, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $73, $4e, $fc
DB $83, $74, $4e, $fe, $1e, $4e, $ff, $81, $4e, $00, $81, $4e, $fe, $81, $73, $4e, $fd, $81, $4e, $fc, $81, $7b, $4e, $fd
DB $80, $0f, $4e, $fe, $81, $7a, $4e, $00, $82, $0f
.song0ref3134:
DB $4e, $ff, $81, $79, $4e, $fe, $81, $4e, $fc, $81, $78, $81, $4e, $fe, $81, $77, $4e, $00, $83, $76
.song0ref3154:
DB $4e, $fe, $81, $4e, $fc, $81, $75, $84, $1e
.song0ref3163:
DB $4e, $fd, $81, $4e, $ff, $81, $4e, $00, $81, $74, $4e, $ff, $81, $4e, $fd, $81, $4e, $fc, $83, $73, $4e, $fe, $81, $4e
DB $00, $81, $4e, $ff, $81, $4e, $fe, $81, $72
DB $41, $09
DW .song0ref119
.song0ref3199:
DB $4e, $00, $81, $4e, $ff, $81, $7b, $4e, $fe, $80, $0f, $4e, $fc, $81, $7a, $82, $0f
.song0ref3216:
DB $4e, $fe, $81, $79, $4e, $00, $83, $78, $4e, $fe, $81, $4e, $fc, $81, $77, $81, $4e, $fd, $81, $76, $4e, $ff, $81, $4e
DB $00, $81, $7b, $4e, $ff, $80, $0d, $4e, $fd, $81, $7a, $4e, $fc, $82, $0d, $81, $79, $4e, $fe, $81, $4e, $00, $81, $78
DB $4e, $ff, $81, $4e, $fe, $81, $77, $4e, $fc, $83, $76, $4e, $fe, $81, $4e, $ff, $81, $7b, $4e, $00, $80, $0f, $4e, $fe
DB $81, $7a, $4e, $fd, $82, $0f, $4e, $fc, $81, $79, $4e, $fd, $81, $4e, $fe, $81, $75, $4e, $00, $84, $1e, $4e, $ff, $81
DB $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $2e
DW .song0ref3040
DB $72
DB $41, $09
DW .song0ref119
DB $41, $18
DW .song0ref3199
.song0ref3329:
DB $7b, $4e, $00, $80, $0a, $4e, $fe, $81, $7a, $4e, $fd, $82, $0a, $4e, $fc, $81, $79, $4e, $fd, $81, $4e, $fe, $81, $75
DB $4e, $00, $84, $1b, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0d
DW .song0ref3040
.song0ref3370:
DB $75, $4e, $fe, $84, $1d
.song0ref3375:
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $74, $4e, $fc, $83, $4e, $fe, $81, $4e, $ff, $81, $73
.song0ref3395:
DB $4e, $00, $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $81, $7b, $4e, $fd, $80, $0f, $4e, $fe, $81, $7a, $4e, $00, $82
DB $0f, $4e, $ff, $81, $79, $4e, $fe, $81, $4e, $fc, $81, $75, $84, $1d
.song0ref3433:
DB $4e, $fe, $81, $4e, $00, $83, $74, $4e, $fe, $81, $4e, $fc, $83, $4e, $fd, $81, $73, $4e, $ff, $81, $4e, $00, $81, $4e
DB $ff, $81, $4e, $fd, $81, $72, $4e, $fc, $83
DB $41, $0d
DW .song0ref107
DB $41, $1e
DW .song0ref3199
DB $75, $4e, $00, $84, $20, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0d
DW .song0ref3040
DB $75, $4e, $fe, $84, $1e
DB $41, $10
DW .song0ref3375
DB $75, $84, $1e
DB $41, $0a
DW .song0ref3433
DB $41, $0d
DW .song0ref107
.song0ref3507:
DB $4e, $00, $81, $4e, $ff, $81, $7a, $4e, $fe, $0f, $4e, $fc, $10, $79, $11, $4e, $fe, $12, $78, $4e, $00, $83, $4e, $fe
DB $81, $4e, $fc, $83, $4e, $fd, $81, $4e, $ff, $81, $4e, $00, $81, $7a, $4e, $ff, $80, $14, $4e, $fd, $81, $4e, $fc, $83
DB $79, $4e, $fe, $81, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $78, $4e, $fc, $83, $77, $4e, $fe, $81, $4e, $ff, $81
DB $7a, $4e, $00, $16, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $81, $79, $4e, $fd, $81, $4e, $fe, $81, $4e, $00, $81, $4e
DB $ff, $81, $78, $4e, $fe, $81, $4e, $fc, $81, $77, $81, $4e, $fe, $81, $7b, $4e, $00
DB $41, $2c
DW .song0ref3048
DB $72
DB $41, $09
DW .song0ref119
DB $41, $22
DW .song0ref3199
DB $74
DB $41, $2e
DW .song0ref3040
DB $72
DB $41, $09
DW .song0ref119
DB $41, $18
DW .song0ref3199
DB $41, $0a
DW .song0ref3329
DB $74
DB $41, $0d
DW .song0ref3040
DB $41, $1c
DW .song0ref3370
DB $41, $0d
DW .song0ref107
DB $41, $1e
DW .song0ref3199
DB $75, $4e, $00, $84, $22, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0d
DW .song0ref3040
DB $75, $4e, $fe, $84, $22
DB $41, $10
DW .song0ref3375
DB $75, $84, $22
DB $41, $0a
DW .song0ref3433
DB $41, $0d
DW .song0ref107
DB $4e, $00, $81, $4e, $ff, $81, $7b, $4e, $fe, $80, $0a, $4e, $fc, $81, $7a, $82, $0a
DB $41, $19
DW .song0ref3216
.song0ref3712:
DB $78, $4e, $00, $81, $4e, $ff, $81, $77, $4e, $fe, $81, $4e, $fc, $81, $76
.song0ref3727:
DB $81, $4e, $fe, $81, $7b, $4e, $00, $80, $12, $81, $7a, $4e, $fe, $82, $12, $4e, $fc, $81, $79, $81, $4e, $fd, $81, $7b
DB $4e, $ff, $80, $14, $4e, $00, $81, $7a, $4e, $ff, $82, $14
DB $41, $0d
DW .song0ref3076
DB $7b, $4e, $fd, $80, $14, $4e, $fe, $81, $7a, $4e, $00, $82, $14
DB $41, $13
DW .song0ref3134
DB $72
DB $41, $09
DW .song0ref119
.song0ref3786:
DB $4e, $00, $81, $4e, $ff, $81, $7b, $4e, $fe, $80, $14, $4e, $fc, $81, $7a, $82, $14, $4e, $fe, $81, $79, $4e, $00, $83
DB $78, $4e, $fe, $81, $4e, $fc, $81, $77, $81, $4e, $fd, $81, $76, $4e, $ff, $81, $4e, $00, $81, $7b, $4e, $ff, $80, $12
DB $4e, $fd, $81, $7a, $4e, $fc, $82, $12, $81, $79, $4e, $fe, $81, $4e, $00, $81, $78, $4e, $ff, $81, $4e, $fe, $81, $77
DB $4e, $fc, $83, $76, $4e, $fe, $81, $4e, $ff, $81, $7b, $4e, $00, $80, $14, $4e, $fe, $81, $7a, $4e, $fd, $82, $14, $4e
DB $fc, $81, $79, $4e, $fd, $81, $4e, $fe, $81, $75, $4e, $00, $84, $20, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0b
DW .song0ref3727
DB $41, $0d
DW .song0ref3076
.song0ref3912:
DB $4e, $fd, $81, $4e, $fe, $81, $72, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $7b, $80, $14, $4e, $fe
DB $81, $7a, $4e, $00, $82, $14, $81, $79
DB $41, $0d
DW .song0ref3154
DB $72
DB $41, $09
DW .song0ref119
DB $41, $13
DW .song0ref3786
.song0ref3954:
DB $75, $4e, $ff, $84, $19
.song0ref3959:
DB $4e, $fe, $81, $4e, $fc, $83, $74, $4e, $fe, $81, $4e, $ff, $81, $7b, $4e, $00, $80, $14, $4e, $fe, $81, $7a, $4e, $fd
DB $82, $14, $4e, $fc, $81, $79, $4e, $fd, $81, $4e, $fe, $81, $75, $4e, $00, $84, $1b, $4e, $ff, $81, $4e, $fe, $81, $4e
DB $fc, $81, $74
DB $41, $0b
DW .song0ref3727
DB $41, $0d
DW .song0ref3076
DB $7b, $4e, $fd, $80, $14, $4e, $fe, $81, $7a, $4e, $00, $82, $14
DB $41, $13
DW .song0ref3134
DB $72
DB $41, $09
DW .song0ref119
DB $41, $1e
DW .song0ref3786
DB $75, $4e, $00, $84, $22, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0b
DW .song0ref3727
DB $4e, $fd, $81, $79, $4e, $fc, $83, $75, $4e, $fe, $84, $20
DB $41, $0a
DW .song0ref3375
DB $7b, $4e, $fd, $80, $14, $4e, $fe, $81, $7a, $4e, $00, $82, $14, $4e, $ff, $81, $79, $4e, $fe, $81, $4e, $fc, $81, $75
DB $84, $20
DB $41, $0a
DW .song0ref3433
DB $41, $0d
DW .song0ref107
.song0ref4104:
DB $4e, $00, $81, $4e, $ff, $81, $7b, $4e, $fe, $80, $14, $4e, $fc, $81, $7a, $82, $14, $4e, $fe, $81, $79, $4e, $00, $83
DB $75, $4e, $fe, $84, $20, $4e, $fc, $83, $4e, $fd, $81, $74, $4e, $ff, $81, $4e, $00, $81, $7b, $4e, $ff, $80, $12, $4e
DB $fd, $81, $7a, $4e, $fc, $82, $12, $81, $79, $4e, $fe, $81, $4e, $00, $81, $75, $4e, $ff, $84, $1b
DB $41, $0e
DW .song0ref3959
.song0ref4175:
DB $74, $81, $4e, $fe, $81, $7b, $4e, $00, $80, $14, $81, $7a, $4e, $fe, $82, $14, $4e, $fc, $81, $79, $81, $4e, $fd, $81
DB $7b, $4e, $ff, $80, $16, $4e, $00, $81, $7a, $4e, $ff, $82, $16, $4e, $fd, $81, $79, $4e, $fc, $83, $74, $4e, $fe, $84
DB $1e, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $73, $4e, $fc, $83, $74, $4e, $fe, $20
.song0ref4241:
DB $4e, $ff, $81, $4e, $00, $81, $4e, $fe, $81, $73, $4e, $fd, $81, $4e, $fc, $81, $7b, $4e, $fd, $80, $16, $4e, $fe, $81
DB $7a, $4e, $00, $82, $16, $4e, $ff, $81, $79, $4e, $fe, $81, $4e, $fc, $81, $78, $81, $4e, $fe, $81, $77, $4e, $00, $83
DB $76, $4e, $fe, $81, $4e, $fc, $81, $75, $84, $20
DB $41, $0a
DW .song0ref3163
DB $72
DB $41, $09
DW .song0ref119
.song0ref4306:
DB $4e, $00, $81, $4e, $ff, $81, $7b, $4e, $fe, $80, $16, $4e, $fc, $81, $7a, $82, $16, $4e, $fe, $81, $79, $4e, $00, $83
DB $78, $4e, $fe, $81, $4e, $fc, $81, $77, $81, $4e, $fd, $81, $76
.song0ref4343:
DB $4e, $ff, $81, $4e, $00, $81, $7b, $4e, $ff, $80, $14, $4e, $fd, $81, $7a, $4e, $fc, $82, $14, $81, $79, $4e, $fe, $81
DB $4e, $00, $81, $75, $4e, $ff, $84, $22, $4e, $fe, $81, $4e, $fc, $83, $74, $4e, $fe, $81, $4e, $ff, $81, $7b, $4e, $00
DB $80, $16, $4e, $fe, $81, $7a, $4e, $fd, $82, $16, $4e, $fc, $81, $79, $4e, $fd, $81, $4e, $fe, $81, $75, $4e, $00, $84
DB $25, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81
DB $41, $24
DW .song0ref4175
DB $41, $0a
DW .song0ref3163
DB $72
DB $41, $09
DW .song0ref119
DB $41, $22
DW .song0ref4306
DB $41, $0d
DW .song0ref4175
DB $74, $4e, $fe, $84, $25, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $73, $4e, $fc, $83, $74, $4e, $fe, $27
DB $41, $0b
DW .song0ref4241
.song0ref4466:
DB $74, $84, $25, $4e, $fe, $81, $4e, $00, $83, $73, $4e, $fe, $81, $4e, $fc, $81, $74, $27, $4e, $fd, $81, $4e, $ff, $81
DB $4e, $00, $81, $73, $4e, $ff, $81, $4e, $fd, $81, $4e, $fc, $83, $72, $4e, $fe, $81, $4e, $00, $81, $4e, $ff, $81, $4e
DB $fe, $81, $75, $4e, $fc, $25, $81, $4e, $fe, $81, $4e, $ff, $81, $74, $4e, $00, $81, $4e, $fe, $81, $75, $4e, $fd, $27
.song0ref4538:
DB $4e, $fc, $81, $4e, $fd, $81, $4e, $fe, $81, $74, $4e, $00, $81, $4e, $ff, $81, $7b, $4e, $fe, $80, $16, $4e, $fc, $81
DB $7a, $82, $16, $4e, $fe, $81, $79, $4e, $00, $83, $75, $4e, $fe, $84, $25, $4e, $fc, $83, $4e, $fd, $81, $74
DB $41, $13
DW .song0ref4343
DB $75, $4e, $00, $84, $20, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81
DB $41, $0d
DW .song0ref4175
.song0ref4604:
DB $75, $4e, $fe, $84, $27, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $74, $4e, $fc, $83, $75, $4e, $fe, $25, $4e, $ff
DB $81, $4e, $00, $81, $4e, $fe, $81, $74, $4e, $fd, $81, $4e, $fc, $81, $7b, $4e, $fd, $80, $16, $4e, $fe, $81, $7a, $4e
DB $00, $82, $16, $4e, $ff, $81, $79, $4e, $fe, $81, $4e, $fc, $81, $75, $84, $20, $4e, $fe, $81, $4e, $00, $83, $74, $4e
DB $fe, $81, $4e, $fc, $81, $75, $25, $4e, $fd, $81, $4e, $ff, $81, $4e, $00, $81, $74, $4e, $ff, $81, $4e, $fd, $81, $75
DB $4e, $fc, $22, $81, $4e, $fe, $81, $4e, $00, $81, $74, $4e, $ff, $81, $4e, $fe, $81, $75, $4e, $fc, $20, $81, $4e, $fe
DB $81, $4e, $ff, $81, $74, $4e, $00, $81, $4e, $fe, $81, $75, $4e, $fd, $1e
DB $41, $0a
DW .song0ref4538
.song0ref4742:
DB $75, $4e, $fe, $84, $20, $4e, $fc, $83, $4e, $fd, $81, $74, $4e, $ff, $81, $4e, $00, $81, $7b, $4e, $ff, $80, $14, $4e
DB $fd, $81, $7a, $4e, $fc, $82, $14, $81, $79, $4e, $fe, $81, $4e, $00, $81, $75, $4e, $ff, $84, $1b, $4e, $fe, $81, $4e
DB $fc, $83, $74, $4e, $fe, $81, $4e, $ff, $81, $7b, $4e, $00, $80, $12, $4e, $fe, $81, $7a, $4e, $fd, $82, $12, $4e, $fc
DB $81, $79, $4e, $fd, $81, $4e, $fe, $81, $75, $4e, $00, $84, $1e, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0d
DW .song0ref3040
DB $74, $4e, $fe, $84, $1b, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $73, $4e, $fc, $83, $4e, $fe, $81, $4e, $ff, $81
DB $72
DB $41, $0a
DW .song0ref3395
.song0ref4868:
DB $75, $84, $1b, $4e, $fe, $81, $4e, $00, $83, $74, $4e, $fe, $81, $4e, $fc, $81, $4e, $f7, $83, $73, $4e, $f9, $81, $4e
DB $fb, $81, $4e, $fe, $81, $4e, $00, $81, $72, $81, $4e, $fe, $81, $4e, $fb, $81, $4e, $fa, $81, $4e, $f7, $83, $4e, $f8
DB $81, $4e, $fa, $81, $4e, $fc, $81, $4e, $ff, $81, $4e, $00, $81, $4e, $ff, $81, $4e, $fd, $81, $4e, $fb, $81, $4e, $f9
DB $81, $4e, $f7, $83
DB $41, $09
DW .song0ref1414
.song0ref4947:
DB $4e, $f7, $83, $4e, $f9, $81, $4e, $fb, $81, $7b, $4e, $00, $80, $0d, $81, $7a, $82, $0d, $81, $79, $83, $78, $83, $77
DB $83, $76
.song0ref4973:
DB $83, $7b, $80, $0f, $81, $7a, $82, $0f, $81, $79, $83, $75, $80, $0d, $81, $82, $0d, $81, $74, $83, $7b, $80, $0d, $81
DB $7a, $82, $0d, $81, $79
DB $41, $0b
DW .song0ref4973
.song0ref5005:
DB $75, $80, $0f, $81, $82, $0f, $81, $74, $83, $75, $80, $0f, $81, $82, $0f, $81, $74, $87, $73, $87, $75, $80, $0f, $81
DB $82, $0f, $81, $74, $87, $73, $87, $77, $80, $0f, $81, $76, $82, $0f, $85, $75, $83, $74, $87, $73, $4e, $f3, $0e, $4e
DB $13, $81, $72, $4e, $03, $0d, $4e, $f0, $0c, $4e, $10, $81, $4e, $fa, $0b, $4e, $1a, $81, $4e, $01, $0a, $4e, $e5, $09
DB $4e, $05, $81, $4e, $e5, $08, $4e, $05, $81, $00, $4e, $00, $ad
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $41, $0a
DW .song0ref2678
DB $89
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $41, $09
DW .song0ref2715
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $41, $0a
DW .song0ref2678
DB $89
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $7c, $4e, $ff, $84, $0a, $4e, $fd, $0b, $7b, $4e, $fc, $0c, $0d
DB $41, $0d
DW .song0ref106
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00
DB $41, $0d
DW .song0ref2680
DB $41, $0d
DW .song0ref2678
DB $41, $0a
DW .song0ref2678
DB $89
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $41, $09
DW .song0ref2715
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $41, $0a
DW .song0ref2678
DB $89
DB $41, $0d
DW .song0ref2678
DB $41, $0d
DW .song0ref2678
DB $7c, $4e, $ff, $84, $16, $4e, $fd, $17, $7b, $4e, $fc, $18, $19
DB $41, $0d
DW .song0ref106
DB $41, $14
DW .song0ref2832
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2879
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2905
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2879
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c, $4e, $ff, $84, $18, $4e, $fd, $19, $7b, $4e, $fc, $1a, $1b
DB $41, $0d
DW .song0ref106
DB $74, $4e, $00, $18, $4e, $ff, $19, $4e, $fe, $1a, $4e, $fc, $1b
DB $41, $10
DW .song0ref2845
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2879
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2905
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $41, $0a
DW .song0ref2879
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c
DB $41, $0e
DW .song0ref2853
DB $7c, $4e, $ff, $84, $18, $4e, $fd, $19, $7b, $4e, $fc, $1a, $1b
DB $41, $0d
DW .song0ref106
DB $41, $32
DW .song0ref3027
DB $72
DB $41, $09
DW .song0ref119
DB $41, $22
DW .song0ref3199
DB $74
DB $41, $2e
DW .song0ref3040
DB $72
DB $41, $09
DW .song0ref119
DB $41, $18
DW .song0ref3199
DB $41, $0a
DW .song0ref3329
DB $74
DB $41, $0d
DW .song0ref3040
DB $41, $1c
DW .song0ref3370
DB $41, $0d
DW .song0ref107
DB $41, $1e
DW .song0ref3199
DB $75, $4e, $00, $84, $20, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0d
DW .song0ref3040
DB $75, $4e, $fe, $84, $1e
DB $41, $10
DW .song0ref3375
DB $75, $84, $1e
DB $41, $0a
DW .song0ref3433
DB $41, $0d
DW .song0ref107
DB $41, $22
DW .song0ref3507
DB $7b, $4e, $00
DB $41, $2c
DW .song0ref3048
DB $72
DB $41, $09
DW .song0ref119
DB $41, $22
DW .song0ref3199
DB $74
DB $41, $2e
DW .song0ref3040
DB $72
DB $41, $09
DW .song0ref119
DB $41, $18
DW .song0ref3199
DB $41, $0a
DW .song0ref3329
DB $74
DB $41, $0d
DW .song0ref3040
DB $41, $1c
DW .song0ref3370
DB $41, $0d
DW .song0ref107
DB $41, $1e
DW .song0ref3199
DB $75, $4e, $00, $84, $22, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0d
DW .song0ref3040
DB $75, $4e, $fe, $84, $22
DB $41, $10
DW .song0ref3375
DB $75, $84, $22
DB $41, $0a
DW .song0ref3433
DB $41, $0d
DW .song0ref107
DB $4e, $00, $81, $4e, $ff, $81, $7b, $4e, $fe, $80, $0a, $4e, $fc, $81, $7a, $82, $0a
DB $41, $19
DW .song0ref3216
DB $41, $0f
DW .song0ref3712
DB $41, $0d
DW .song0ref3076
DB $7b, $4e, $fd, $80, $14, $4e, $fe, $81, $7a, $4e, $00, $82, $14
DB $41, $13
DW .song0ref3134
DB $72
DB $41, $09
DW .song0ref119
DB $41, $22
DW .song0ref3786
DB $74
DB $41, $0b
DW .song0ref3727
DB $41, $0d
DW .song0ref3076
DB $41, $0a
DW .song0ref3912
DB $79
DB $41, $0d
DW .song0ref3154
DB $72
DB $41, $09
DW .song0ref119
DB $41, $13
DW .song0ref3786
DB $41, $0f
DW .song0ref3954
DB $74
DB $41, $0b
DW .song0ref3727
DB $41, $0d
DW .song0ref3076
DB $7b, $4e, $fd, $80, $14, $4e, $fe, $81, $7a, $4e, $00, $82, $14
DB $41, $13
DW .song0ref3134
DB $72
DB $41, $09
DW .song0ref119
DB $41, $1e
DW .song0ref3786
DB $75, $4e, $00, $84, $22, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81, $74
DB $41, $0b
DW .song0ref3727
DB $4e, $fd, $81, $79, $4e, $fc, $83, $75, $4e, $fe, $84, $20
DB $41, $0a
DW .song0ref3375
DB $7b, $4e, $fd, $80, $14, $4e, $fe, $81, $7a, $4e, $00, $82, $14, $4e, $ff, $81, $79, $4e, $fe, $81, $4e, $fc, $81, $75
DB $84, $20
DB $41, $0a
DW .song0ref3433
DB $41, $0d
DW .song0ref107
DB $41, $13
DW .song0ref4104
DB $41, $0e
DW .song0ref3959
DB $41, $24
DW .song0ref4175
DB $41, $0a
DW .song0ref3163
DB $72
DB $41, $09
DW .song0ref119
DB $41, $22
DW .song0ref4306
DB $41, $24
DW .song0ref4175
DB $41, $0a
DW .song0ref3163
DB $72
DB $41, $09
DW .song0ref119
DB $41, $22
DW .song0ref4306
DB $41, $0d
DW .song0ref4175
DB $74, $4e, $fe, $84, $25, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $73, $4e, $fc, $83, $74, $4e, $fe, $27
DB $41, $0b
DW .song0ref4241
DB $41, $24
DW .song0ref4466
DB $74
DB $41, $13
DW .song0ref4343
DB $75, $4e, $00, $84, $20, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $81
DB $41, $0d
DW .song0ref4175
DB $41, $29
DW .song0ref4604
DB $41, $0a
DW .song0ref4538
DB $41, $1a
DW .song0ref4742
DB $74
DB $41, $0d
DW .song0ref3040
DB $74, $4e, $fe, $84, $1b, $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $73, $4e, $fc, $83, $4e, $fe, $81, $4e, $ff, $81
DB $72
DB $41, $0a
DW .song0ref3395
DB $41, $19
DW .song0ref4868
DB $41, $09
DW .song0ref1414
DB $41, $19
DW .song0ref4947
DB $79
DB $41, $0b
DW .song0ref4973
DB $41, $24
DW .song0ref5005
DB $4e, $00, $c5, $76, $4e, $02, $80, $0d, $85, $75, $83, $76, $4e, $fc, $81, $4e, $f4, $81, $4e, $ec, $81, $4e, $14, $0e
DB $75, $4e, $0c, $81, $4e, $04, $81, $4e, $fc, $81, $4e, $f4, $81, $74, $4e, $ec, $81, $4e, $11, $0f, $4e, $09, $81, $4e
DB $01, $81, $4e, $00, $a3, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81
DB $41, $0c
DW .song0ref892
DB $4e, $fc, $85, $4e, $fe, $83
DB $41, $09
DW .song0ref2227
DB $41, $0a
DW .song0ref898
DB $4e, $fc, $85, $4e, $fe, $83
DB $41, $09
DW .song0ref2227
DB $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $83, $81, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff
DB $81, $4e, $fe, $81, $4e, $fd, $81, $4e, $fc, $85, $4e, $fe, $83
DB $41, $09
DW .song0ref2227
DB $76, $4e, $02, $87, $75, $87, $74, $87, $72, $97, $76, $0d, $85, $75, $87, $74, $87
.song0ref5945:
DB $76, $12, $85, $75, $87, $74, $87
.song0ref5952:
DB $4e, $01, $81, $4e, $00, $83, $4e, $fe, $85
.song0ref5961:
DB $4e, $ff, $81, $4e, $00, $81, $4e, $01, $81, $4e, $02, $83, $4e, $01, $81
.song0ref5976:
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $85, $4e, $ff, $81, $4e, $00, $81, $4e, $01, $81, $4e, $02, $83, $4e, $01, $81
DB $4e, $00, $81, $76, $4e, $02, $11, $85, $75, $87, $74, $87, $76, $4e, $fc, $10, $4e, $f1, $0f, $4e, $11, $81, $4e, $04
DB $0e, $75, $4e, $f4, $0d, $4e, $00, $85, $74, $9f, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $4e, $fd, $81, $4e, $fe
DB $81, $4e, $ff, $81
DB $41, $0c
DW .song0ref892
DB $4e, $fc, $85, $4e, $fe, $83, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $81, $76, $4e, $02, $14, $85, $75
DB $87, $74, $9f
DB $41, $15
DW .song0ref5945
DB $76, $4e, $02, $0d, $85, $75, $87, $74, $9f, $72, $97, $76, $87, $75, $83, $76, $4e, $f4, $81, $4e, $14, $0e, $4e, $04
DB $81, $4e, $f4, $81, $75, $4e, $11, $0f, $4e, $01, $81, $4e, $00, $83, $74, $93, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc
DB $85, $4e, $fd, $81, $4e, $fe, $81, $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $7a, $4e, $00, $14, $87, $79, $8d, $7a
DB $12, $87, $79, $8d, $77, $83, $76, $93, $7a, $89, $79, $81, $7a, $4e, $f0, $81, $4e, $04, $13, $4e, $f4, $81, $4e, $06
DB $14, $4e, $00, $81, $79, $91, $78, $87, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $85, $77, $4e, $fd, $81, $4e, $fe, $81
DB $4e, $ff, $81, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $81, $76
DB $41, $0a
DW .song0ref901
DB $75, $83, $4e, $fe, $83, $4e, $00, $83, $4e, $ff, $81, $4e, $fe, $83, $4e, $fc, $81, $76, $4e, $fe, $83, $4e, $ff, $81
DB $4e, $00, $81, $75, $4e, $01, $81, $4e, $02, $83, $4e, $01, $81, $74
DB $41, $09
DW .song0ref5976
DB $4e, $ff, $81, $4e, $fe, $85, $76, $4e, $02, $0f, $85, $75, $87, $74, $87, $76, $11, $85, $75, $87, $74, $87, $76, $12
DB $85, $75, $87, $74, $87, $72, $97, $76, $11, $85, $75, $87, $74, $87, $76, $0d, $85, $75, $87, $74, $9f, $4e, $01, $81
DB $4e, $00, $83, $4e, $fe, $81, $83
DB $41, $0e
DW .song0ref5961
DB $4e, $ff, $81, $4e, $fe, $85, $4e, $00, $83, $4e, $02, $83
DB $41, $0a
DW .song0ref5952
DB $4e, $fe, $ff, $ff, $ff, $ab, $42
DW .song0ch1loop
.song0ch2:
.song0ch2loop:
DB $84
.song0ref6346:
DB $19, $81
.song0ref6348:
DB $0d, $85, $0f
.song0ref6351:
DB $89, $00, $95, $1b, $81, $0f, $85, $00, $89
DB $41, $0e
DW .song0ref6346
DB $19, $81, $0d, $85, $0f, $89, $00, $95
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $22, $81, $16, $91, $24, $81, $18, $91
DB $41, $0e
DW .song0ref6346
DB $41, $0b
DW .song0ref6346
.song0ref6391:
DB $81, $83, $00, $89, $19, $81, $0d, $85, $0f, $89, $00, $95
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $4e, $ff, $25, $4e, $fd, $81, $4e, $fc, $19, $81
DB $41, $0d
DW .song0ref107
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $83
DB $41, $0c
DW .song0ref6348
DB $41, $0e
DW .song0ref6346
DB $19, $81, $0d, $85, $0f, $89, $00, $95
DB $41, $0d
DW .song0ref6346
DB $81, $87
DB $41, $0e
DW .song0ref6346
DB $22, $81, $16, $91, $24, $81, $18, $91
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $19, $81, $0d, $85, $0f, $89, $00, $95
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $4e, $ff, $25, $4e, $fd, $81, $4e, $fc, $19, $81
DB $41, $0d
DW .song0ref107
.song0ref6503:
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $83
.song0ref6521:
DB $0d, $85, $0f, $95
.song0ref6525:
DB $00, $89, $1b, $81, $0f, $85, $00, $89, $19, $81
DB $41, $0e
DW .song0ref6521
DB $0d, $85, $0f, $95, $00, $89, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $0c
DW .song0ref6521
.song0ref6552:
DB $20, $81, $14, $91, $1b, $81, $0f, $85, $00, $89, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $09
DW .song0ref6521
DB $41, $09
DW .song0ref6391
DB $95, $00, $89, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $0c
DW .song0ref6521
DB $4e, $ff, $22, $4e, $fd, $81, $4e, $fc, $16, $81
DB $41, $0d
DW .song0ref107
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $0e
DW .song0ref6521
DB $0d, $85, $0f, $95, $00, $89, $19, $81
DB $41, $0b
DW .song0ref6521
DB $81, $87, $19, $81
DB $41, $0c
DW .song0ref6521
DB $41, $0c
DW .song0ref6552
DB $41, $0e
DW .song0ref6521
DB $41, $0e
DW .song0ref6521
DB $0d, $85, $0f, $95, $00, $89, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $0c
DW .song0ref6348
DB $4e, $ff, $27, $4e, $fd, $81, $4e, $fc, $1b, $81
DB $41, $0d
DW .song0ref107
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $19, $81
DB $41, $09
DW .song0ref6521
.song0ref6698:
DB $91
.song0ref6699:
DB $00, $ad, $1b, $81, $0f, $85, $00, $89, $19, $81, $0d, $85
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
DB $41, $0d
DW .song0ref6698
.song0ref6720:
DB $00, $89, $16, $81, $0a, $85, $00, $89, $19, $81
DB $41, $09
DW .song0ref6521
.song0ref6733:
DB $91, $00, $ad, $1b, $81, $0f, $81, $83, $00, $89, $19, $81, $0d, $85
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
DB $91
.song0ref6754:
DB $00, $ad, $1e, $81, $12, $91, $20, $81, $14, $91, $22, $81, $16, $91, $19, $81
DB $41, $09
DW .song0ref6521
DB $41, $0d
DW .song0ref6698
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
DB $89, $87
DB $41, $0c
DW .song0ref6699
DB $41, $0a
DW .song0ref6720
DB $41, $09
DW .song0ref6521
DB $41, $0d
DW .song0ref6698
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
.song0ref6802:
DB $91, $00, $ad, $16, $81, $0a, $91, $19, $81, $0d, $91, $1b, $81, $0f, $91, $1e, $81, $12, $85
.song0ref6821:
DB $14, $95, $00, $89, $20, $81, $14, $91, $00, $ad
.song0ref6831:
DB $20, $81, $14, $85, $00, $89, $1e, $81, $12, $85, $00, $89
DB $41, $0a
DW .song0ref6831
DB $41, $16
DW .song0ref6821
DB $41, $0a
DW .song0ref6831
DB $41, $0d
DW .song0ref6821
.song0ref6855:
DB $81, $83, $00, $89, $1e, $81, $12, $85, $00, $89
DB $41, $0a
DW .song0ref6831
DB $41, $0d
DW .song0ref6821
.song0ref6871:
DB $91, $1e, $81, $12, $91, $20, $81, $14, $91, $20, $81, $14, $85
.song0ref6884:
DB $16, $95, $00, $89, $22, $81, $16, $91
.song0ref6892:
DB $00, $ad
.song0ref6894:
DB $22, $81, $16, $85, $00, $89, $20, $81, $14, $85, $00, $89
DB $41, $0a
DW .song0ref6894
DB $16, $95, $00, $89, $22, $81, $16, $89, $87
DB $41, $0e
DW .song0ref6892
DB $41, $0a
DW .song0ref6894
DB $41, $16
DW .song0ref6884
DB $41, $0a
DW .song0ref6894
DB $41, $0d
DW .song0ref6884
.song0ref6933:
DB $91, $20, $81, $14, $91, $1e, $81, $12, $91, $19, $81
DB $41, $09
DW .song0ref6521
DB $91, $00, $c5, $19, $81, $0d, $85
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
.song0ref6960:
DB $91, $00, $95, $1b, $81, $0f, $91, $4e, $10, $81, $4e, $f3, $0e, $4e, $03, $81, $4e, $13, $81, $4e, $f3, $0d, $4e, $03
DB $81, $4e, $13, $81, $4e, $f0, $0c, $4e, $00, $81, $4e, $10, $81, $4e, $ea, $0b, $4e, $fa, $81, $4e, $0a, $81, $4e, $1a
DB $81, $4e, $f1, $0a, $4e, $01, $81, $4e, $11, $81, $4e, $e5, $09, $4e, $f5, $81, $4e, $05, $81, $4e, $15, $81, $4e, $e5
DB $08, $4e, $f5, $81, $4e, $05, $81, $4e, $15, $81, $4e, $e1, $07, $4e, $f1, $81, $4e, $01, $81, $4e, $11, $81, $4e, $21
DB $81, $4e, $e9, $06, $4e, $f9, $81, $4e, $09, $81, $4e, $19, $81, $4e, $dd, $05, $4e, $ed, $81, $4e, $00
DB $41, $0e
DW .song0ref6346
DB $41, $0b
DW .song0ref6346
DB $41, $0c
DW .song0ref6391
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $22, $81, $16, $91, $24, $81, $18, $91
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $19, $81, $0d, $85, $0f, $89, $00, $95
DB $41, $0d
DW .song0ref6346
DB $81, $87
DB $41, $0e
DW .song0ref6346
DB $4e, $ff, $25, $4e, $fd, $81, $4e, $fc, $19, $81
DB $41, $0d
DW .song0ref107
DB $41, $09
DW .song0ref6503
DB $41, $09
DW .song0ref6351
DB $41, $0e
DW .song0ref6346
DB $19, $81, $0d, $85, $0f, $89, $00, $95
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $22, $81, $16, $91, $24, $81, $18, $91
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $19, $81, $0d, $85, $0f, $89, $00, $95
DB $41, $0e
DW .song0ref6346
DB $41, $0e
DW .song0ref6346
DB $4e, $ff, $25, $4e, $fd, $81, $4e, $fc, $19, $81
DB $41, $0d
DW .song0ref107
DB $41, $14
DW .song0ref6503
DB $41, $09
DW .song0ref6521
DB $41, $09
DW .song0ref6391
DB $95, $00, $89, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $0c
DW .song0ref6521
DB $41, $0c
DW .song0ref6552
DB $41, $0e
DW .song0ref6521
DB $41, $0e
DW .song0ref6521
DB $0d, $85, $0f, $95, $00, $89, $19, $81
DB $41, $0b
DW .song0ref6521
DB $81, $87, $19, $81
DB $41, $0c
DW .song0ref6521
DB $4e, $ff, $22, $4e, $fd, $81, $4e, $fc, $16, $81
DB $41, $0d
DW .song0ref107
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $0e
DW .song0ref6521
DB $0d, $85, $0f, $95, $00, $89, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $0c
DW .song0ref6521
DB $41, $0c
DW .song0ref6552
DB $41, $0e
DW .song0ref6521
DB $41, $0e
DW .song0ref6521
DB $0d, $85, $0f, $95, $00, $89, $19, $81
DB $41, $0e
DW .song0ref6521
DB $41, $0c
DW .song0ref6348
DB $4e, $ff, $27, $4e, $fd, $81, $4e, $fc, $1b, $81
DB $41, $0d
DW .song0ref107
DB $4e, $00, $81, $4e, $ff, $81, $4e, $fe, $81, $4e, $fc, $83, $4e, $fe, $81, $4e, $00, $19, $81
DB $41, $09
DW .song0ref6521
DB $41, $0e
DW .song0ref6733
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
DB $41, $0d
DW .song0ref6698
DB $41, $0a
DW .song0ref6720
DB $41, $09
DW .song0ref6521
DB $41, $0d
DW .song0ref6698
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
DB $89, $87
DB $41, $10
DW .song0ref6754
DB $41, $09
DW .song0ref6521
DB $41, $0d
DW .song0ref6698
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
DB $41, $0d
DW .song0ref6698
DB $41, $0a
DW .song0ref6720
DB $41, $09
DW .song0ref6521
DB $41, $0d
DW .song0ref6698
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
DB $41, $20
DW .song0ref6802
DB $41, $0a
DW .song0ref6855
DB $41, $0a
DW .song0ref6831
DB $41, $16
DW .song0ref6821
DB $41, $0a
DW .song0ref6831
DB $41, $16
DW .song0ref6821
DB $41, $0a
DW .song0ref6831
DB $14, $95, $00, $89, $20, $81, $14, $89, $87, $00, $ad, $20, $81, $14
DB $41, $23
DW .song0ref6871
DB $41, $0a
DW .song0ref6894
DB $41, $16
DW .song0ref6884
DB $41, $0a
DW .song0ref6894
DB $41, $16
DW .song0ref6884
DB $41, $0a
DW .song0ref6894
DB $41, $0d
DW .song0ref6884
DB $41, $0b
DW .song0ref6933
DB $41, $09
DW .song0ref6521
DB $91, $00, $b5, $8f, $19, $81, $0d, $85
DB $41, $0a
DW .song0ref6525
DB $41, $09
DW .song0ref6521
DB $41, $2b
DW .song0ref6960
DB $4e, $00
.song0ref7499:
DB $1b, $81, $0f, $85
.song0ref7503:
DB $1b, $81, $0f, $85, $00, $95, $1b, $81, $0f, $85, $00, $89
DB $41, $10
DW .song0ref7499
DB $41, $0e
DW .song0ref7499
DB $41, $0b
DW .song0ref7503
DB $81, $87
DB $41, $10
DW .song0ref7499
DB $41, $0a
DW .song0ref7499
.song0ref7532:
DB $1e, $81, $12, $85, $1e, $81, $12, $85, $00, $95, $1e, $81, $12, $85, $00, $89
DB $41, $10
DW .song0ref7532
DB $41, $0a
DW .song0ref7532
.song0ref7554:
DB $20, $81, $14, $85, $20, $81, $14, $85, $00, $95, $20, $81, $14, $85, $00, $89
DB $41, $10
DW .song0ref7554
DB $41, $0a
DW .song0ref7554
DB $41, $10
DW .song0ref7499
DB $41, $10
DW .song0ref7499
DB $41, $0e
DW .song0ref7499
DB $41, $0c
DW .song0ref7503
DB $41, $10
DW .song0ref7499
DB $41, $0a
DW .song0ref7499
DB $41, $10
DW .song0ref7532
DB $41, $0d
DW .song0ref7532
DB $81, $83, $00, $89
DB $41, $0a
DW .song0ref7532
DB $20, $81, $14, $85, $20, $81, $14, $ff, $ff, $ff, $ad, $42
DW .song0ch2loop
.song0ch3:
.song0ch3loop:
DB $7c, $84
.song0ref7624:
DB $23, $76, $81, $74, $83, $73, $83, $72, $83, $71, $83, $00, $99, $7c, $22, $76, $81, $74, $83, $73, $83, $72, $83, $71
DB $83, $00, $99, $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $10
DW .song0ref7624
DB $7c, $23, $76, $81, $74, $83, $73, $83, $72, $83, $71, $83, $00, $89, $8f, $7c, $22, $76, $81, $74, $83, $73, $83, $72
DB $83, $71, $83, $00, $99, $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $09
DW .song0ref7624
.song0ref7704:
DB $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81, $75, $87, $74, $89, $73, $89, $72, $83, $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $10
DW .song0ref7624
DB $7c
DB $41, $10
DW .song0ref7624
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $21
DB $41, $09
DW .song0ref7704
DB $7c, $20
DB $41, $09
DW .song0ref7704
.song0ref7766:
DB $7c, $22, $76, $81, $74, $83, $73, $83, $7a, $23, $75, $81, $73, $83, $72, $83
.song0ref7782:
DB $78, $20, $76, $83, $75, $83
.song0ref7788:
DB $74, $85, $73
.song0ref7791:
DB $87, $7c, $22, $76, $81, $74, $83, $73, $83, $7a, $23, $75, $81, $73, $83, $72, $83, $7c, $81, $7a, $81, $79, $81, $78
DB $83, $77, $83, $76, $81, $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $78, $20, $76, $83, $75, $81, $81
DB $41, $10
DW .song0ref7788
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
.song0ref7869:
DB $75, $87, $7c, $81, $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81, $75, $87, $78, $20, $76, $83, $75, $83, $74, $85
DB $73
.song0ref7894:
DB $87, $7c, $22, $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81, $75, $87, $7c, $23, $7a, $81, $79, $81, $78, $83, $77
DB $83, $76, $81, $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $0e
DW .song0ref7894
.song0ref7967:
DB $75, $87, $7c, $22
.song0ref7971:
DB $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81, $75, $87, $7c, $21, $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81
DB $75, $87, $7c, $20
DB $41, $0e
DW .song0ref7971
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
.song0ref8010:
DB $7c, $81, $76, $81, $74, $83, $73, $83, $72, $83, $71, $83
.song0ref8022:
DB $00, $81, $7c, $23
.song0ref8026:
DB $76, $81, $74, $83, $73, $83, $72, $83, $71, $83, $00, $81
.song0ref8038:
DB $7c, $23
.song0ref8040:
DB $76, $81, $74, $83, $73, $83, $72, $83, $71, $83, $00, $81, $7a, $23, $75, $81, $73, $83, $72, $83, $71, $87, $00, $81
DB $7c, $22
DB $41, $16
DW .song0ref8026
.song0ref8069:
DB $7c, $23, $76, $81, $74, $83, $73, $83, $72, $83, $71, $83, $00, $81, $7c, $22
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
.song0ref8091:
DB $76, $81, $74, $83, $73, $83, $72, $83, $71, $83, $00, $81
.song0ref8103:
DB $7c, $23
.song0ref8105:
DB $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81, $75, $87, $7a, $81, $75, $81, $73, $83, $72, $83, $71, $87
DB $41, $0a
DW .song0ref8022
DB $7c, $22
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $16
DW .song0ref8026
DB $41, $09
DW .song0ref8069
DB $41, $0e
DW .song0ref8040
DB $41, $09
DW .song0ref8038
.song0ref8150:
DB $78, $81, $77, $81, $76, $87, $75, $81, $74, $87, $7c, $22, $76, $81, $74, $83, $73, $83, $72, $83, $71, $83
.song0ref8172:
DB $00, $81, $7c, $22, $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81, $75, $87, $7a, $23, $75, $81, $73, $83, $72, $83
DB $71, $87
DB $41, $0a
DW .song0ref8022
DB $7c, $22
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $16
DW .song0ref8026
DB $41, $09
DW .song0ref8069
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $13
DW .song0ref8091
DB $41, $0a
DW .song0ref8022
DB $7c, $22
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $16
DW .song0ref8026
DB $41, $09
DW .song0ref8069
DB $41, $0e
DW .song0ref8040
DB $41, $0c
DW .song0ref8103
DB $41, $09
DW .song0ref8172
.song0ref8250:
DB $74, $89, $73, $89
.song0ref8254:
DB $72, $83
.song0ref8256:
DB $7c, $23
.song0ref8258:
DB $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81, $75, $87
.song0ref8270:
DB $7a, $22, $75, $81, $73, $83, $72, $83, $7a, $81, $75, $81, $73, $83, $72, $83, $7c, $23, $76, $81, $74, $83, $73, $83
DB $7c, $81, $76, $81, $74, $83, $73, $83
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $0f
DW .song0ref8256
DB $7c, $81
DB $41, $0a
DW .song0ref8105
DB $7a, $81, $75, $81, $73, $83
DB $41, $10
DW .song0ref8254
DB $7c, $81
DB $41, $09
DW .song0ref7704
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $0f
DW .song0ref8256
DB $7c, $81
DB $41, $0a
DW .song0ref8105
DB $7a, $81, $75, $81, $73, $83, $72, $83, $7c, $21
DB $41, $0e
DW .song0ref8258
DB $7c, $20
DB $41, $09
DW .song0ref7704
.song0ref8473:
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87, $73, $89, $72, $89, $71, $83, $7a, $23, $78, $81, $77, $81
DB $76, $87, $75, $81, $74, $87, $73, $89, $72, $89, $71, $83, $7b, $22
.song0ref8511:
DB $79, $81, $78, $81, $77, $83, $76, $83, $75, $81, $74, $87, $73, $89, $72, $89, $71, $83, $7b, $23
DB $41, $09
DW .song0ref8511
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $20
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23, $7a, $81, $79, $81, $78, $83, $77, $83, $76, $81, $75, $87, $74, $87, $81, $73, $89, $72, $83, $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $21
DB $41, $09
DW .song0ref7704
DB $7c, $20
DB $41, $09
DW .song0ref7704
DB $7c, $21
DB $41, $09
DW .song0ref7704
DB $7c, $1f
DB $41, $09
DW .song0ref7704
DB $41, $1b
DW .song0ref7766
DB $75
DB $41, $09
DW .song0ref7791
DB $78, $20, $76, $83, $75, $81, $81
DB $41, $10
DW .song0ref7788
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $41, $1a
DW .song0ref7869
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $09
DW .song0ref7791
DB $41, $13
DW .song0ref7782
DB $75
DB $41, $0e
DW .song0ref7894
DB $41, $10
DW .song0ref7967
DB $41, $0e
DW .song0ref7971
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $41, $20
DW .song0ref8010
DB $41, $16
DW .song0ref8026
DB $41, $09
DW .song0ref8069
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $13
DW .song0ref8091
DB $41, $0a
DW .song0ref8022
DB $7c, $22
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $16
DW .song0ref8026
DB $41, $09
DW .song0ref8069
DB $41, $0e
DW .song0ref8040
DB $41, $09
DW .song0ref8038
DB $41, $19
DW .song0ref8150
DB $41, $0a
DW .song0ref8022
DB $7c, $22
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $16
DW .song0ref8026
DB $41, $09
DW .song0ref8069
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $13
DW .song0ref8091
DB $41, $0a
DW .song0ref8022
DB $7c, $22
DB $41, $0e
DW .song0ref8040
DB $41, $10
DW .song0ref8038
DB $41, $16
DW .song0ref8026
DB $41, $09
DW .song0ref8069
DB $41, $0e
DW .song0ref8040
DB $41, $0c
DW .song0ref8103
DB $41, $09
DW .song0ref8172
DB $41, $1a
DW .song0ref8250
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $0f
DW .song0ref8256
DB $7c, $81
DB $41, $0a
DW .song0ref8105
DB $7a, $81, $75, $81, $73, $83
DB $41, $10
DW .song0ref8254
DB $7c, $81
DB $41, $09
DW .song0ref7704
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $17
DW .song0ref8256
DB $41, $10
DW .song0ref8270
DB $41, $10
DW .song0ref8270
DB $7a, $22, $78, $81, $77, $81, $76, $87, $75, $81, $74, $87
DB $41, $0f
DW .song0ref8256
DB $7c, $81
DB $41, $0a
DW .song0ref8105
DB $7a, $81, $75, $81, $73, $83, $72, $83, $7c, $21
DB $41, $0e
DW .song0ref8258
DB $7c, $20
DB $41, $09
DW .song0ref7704
DB $41, $19
DW .song0ref8473
DB $73, $87, $81, $72, $89, $71, $83, $7b, $23
DB $41, $09
DW .song0ref8511
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $23
DB $41, $09
DW .song0ref7704
DB $7c, $22
DB $41, $09
DW .song0ref7704
DB $7c, $20
DB $41, $09
DW .song0ref7704
DB $78, $23
.song0ref9152:
DB $74, $81, $72, $87
.song0ref9156:
DB $76, $81, $73, $81, $72, $83, $71, $83, $78, $22, $74, $81, $72, $87, $76, $23, $73, $81, $72, $83, $71, $83, $76, $22
.song0ref9180:
DB $75, $81, $74, $85, $73, $85, $72, $87, $78, $23, $74, $81, $72, $87, $76, $22, $73, $81, $72, $83, $71, $83, $78, $23
DB $74, $81, $72, $87, $76, $22, $73, $81, $72, $83, $71, $83, $78, $23, $74, $81, $72, $87, $76, $22, $73, $81, $72, $83
DB $71, $83, $76, $81
DB $41, $0e
DW .song0ref9180
DB $41, $26
DW .song0ref9156
DB $41, $0e
DW .song0ref9180
DB $41, $26
DW .song0ref9156
DB $41, $0e
DW .song0ref9180
DB $41, $26
DW .song0ref9156
DB $75, $81, $74, $85, $73, $85, $72, $87, $78, $23, $76, $83, $75, $83, $74, $85, $73, $87, $78, $81
DB $41, $28
DW .song0ref9152
DB $41, $0e
DW .song0ref9180
DB $41, $26
DW .song0ref9156
DB $41, $0e
DW .song0ref9180
DB $41, $20
DW .song0ref9156
DB $72, $83, $83, $76, $22, $73, $81, $72, $83, $71, $83, $76, $81
DB $41, $0e
DW .song0ref9180
DB $76, $81, $73, $81, $72, $83, $71, $ff, $ff, $ff, $ab, $42
DW .song0ch3loop
.song0ch4:
	DB $FF
