
	PLAY FULL
	PLAY teste3
loop:
	WAIT
	GOTO loop

teste3:
	DATA BYTE 2
	MUSIC C2W,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC D2W,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC E2W,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC F2W,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC G2W,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC A2W,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC B2W,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC C3W,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC S,-,-,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,E4Y,C3W,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,E4Y,F3W,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,S,S,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC -,-,C3Y,-
	MUSIC REPEAT
